obj-$(CONFIG_NXP_NFC_I2C) := nxpnfc_i2c.o

nxpnfc_i2c-y := common.o \
             i2c_drv.o

obj-$(CONFIG_NXP_NFC_SPI) := nxpnfc_spi.o

nxpnfc_spi-y := common.o \
				spi_drv.o

ccflags-y += -DCONFIG_NXP_NFC_SPI
ccflags-y += -DCONFIG_NXP_NFC_I2C
ccflags-y += -DDYNAMIC_DEBUG_MODULE