ifeq ($(CONFIG_ARCH_PINEAPPLE), y)
dtbo-y += pineapple-audio.dtbo \
                 pineapple-audio-cdp.dtbo \
                 pineapple-audio-wsa883x-cdp.dtbo \
                 pineapple-audio-cdp-nfc.dtbo \
                 pineapple-audio-mtp.dtbo \
                 pineapple-audio-mtp-nfc.dtbo \
                 pineapple-audio-qrd.dtbo \
                 pineapple-audio-atp.dtbo \
                 pineapple-audio-rumi.dtbo \
                 pineapple-audio-rcm.dtbo \
                 pineapple-audio-qrd-sku2.dtbo \
                 pineapplep-audio-hdk.dtbo
endif

ifeq ($(CONFIG_ARCH_SUN), y)
dtbo-y += sun-audio.dtbo \
                sun-audio-cdp.dtbo \
                sun-audio-cdp-nfc.dtbo \
                sun-audio-rumi.dtbo \
                sun-audio-mtp.dtbo \
                sun-audio-mtp-3.5mm.dtbo \
                sun-audio-mtp-nfc.dtbo \
                sun-audio-mtp-qmp.dtbo \
                sun-audio-qrd.dtbo \
                sun-audio-hdk.dtbo \
                sun-audio-qrd-sku2.dtbo \
                sun-audio-atp.dtbo \
                sun-audio-rcm.dtbo \
                sun-audio-hamilton-rcm.dtbo \
                sun-audio-hamilton-cdp.dtbo \
                sun-audio-hamilton-mtp-v2.dtbo \
                sun-audio-hamilton-mtp.dtbo \
                sun-audio-hamilton-mtp-3.5mm.dtbo
endif

ifeq ($(CONFIG_ARCH_CANOE), y)
dtbo-y += canoe-audio.dtbo \
                canoe-audio-rumi.dtbo \
                canoe-audio-mtp.dtbo \
                canoe-audio-atp.dtbo \
                canoe-audio-mtp-wsa885x.dtbo \
                canoe-audio-cdp-wsa885x.dtbo \
                canoe-audio-cdp-pandeiro-i2s.dtbo \
                canoe-audio-cdp.dtbo \
                canoe-audio-qrd.dtbo \
                canoe-audio-hdk.dtbo \
                canoe-audio-qrd-sku2.dtbo \
                canoe-audio-rcm.dtbo \
                canoe-audio-mtp-qmp.dtbo \
                canoe-audio-mtp-3.5mm.dtbo \
                canoe-audio-mtp-pictor.dtbo \
                canoe-audio-hamilton-mtp.dtbo \
                canoe-audio-hamilton-cdp.dtbo \
                canoe-audio-hamilton-rcm.dtbo \
                alor-interposer-audio-mtp.dtbo \
                alor-interposer-audio-rcm.dtbo \
                alor-interposer-audio-qrd.dtbo \
                alor-audio.dtbo \
                alor-audio-mtp.dtbo \
                alor-audio-mtp-wcd939x.dtbo \
                alor-audio-qrd.dtbo \
                alor-audio-cdp.dtbo \
                alor-audio-atp.dtbo \
                alor-audio-rcm.dtbo \
                alor-audio-rumi.dtbo
endif

ifeq ($(CONFIG_ARCH_VIENNA), y)
dtbo-y += vienna-audio.dtbo
endif

ifeq ($(CONFIG_ARCH_YUPIK), y)
dtbo-y += yupik-iot-audio.dtbo \
                yupik-iot-audio-idp-overlay.dtbo \
                yupik-iot-audio-hsp-overlay.dtbo \
                yupik-iot-audio-qrd-overlay.dtbo \
                yupik-iot-audio-idps-amoled-overlay.dtbo \
                yupikp-iot-audio-hsp-overlay.dtbo \
                yupikp-iot-audio-idp-overlay.dtbo \
                yupikp-iot-audio-idps-amoled-overlay.dtbo \
                yupikp-iot-audio-qrd-overlay.dtbo \
                yupik-iot-audio-rb3-gen2-ck-overlay.dtbo \
                yupik-iot-audio-rb3-gen2-vk-overlay.dtbo \
                yupik-iot-audio-rb3-gen2-vc-overlay.dtbo \
                yupikp-iot-qrd-overlay-bpmc934-dvt_audio.dtbo         \
                yupikp-iot-qrd-overlay-bpmc934-evt2_audio.dtbo        \
                yupikp-iot-qrd-overlay-bpmc934-pvt_audio.dtbo         \
                yupikp-iot-qrd-overlay-lisbonmc9392-dvt_audio.dtbo    \
                yupikp-iot-qrd-overlay-lisbonmc9392-evt2_audio.dtbo   \
                yupikp-iot-qrd-overlay-lisbonmc9392-pvt_audio.dtbo    \
                yupikp-iot-qrd-overlay-slatemc933-dvt_audio.dtbo \
                yupikp-iot-qrd-overlay-slatemc933-evt2_audio.dtbo \
                yupikp-iot-qrd-overlay-slatemc933mipi-dvt_audio.dtbo  \
                yupikp-iot-qrd-overlay-slatemc933mipi-evt2_audio.dtbo \
                yupikp-iot-qrd-overlay-slatemc933mipi-pvt_audio.dtbo  \
                yupikp-iot-qrd-overlay-slatemc933-pvt_audio.dtbo      \
                yupikp-iot-qrd-overlay-stdmc936-dvt_audio.dtbo        \
                yupikp-iot-qrd-overlay-stdmc936-evt2_audio.dtbo \
                yupikp-iot-qrd-overlay-stdmc936-pvt_audio.dtbo \
                yupikp-iot-qrd-overlay-stdmc937-dvt_audio.dtbo \
                yupikp-iot-qrd-overlay-stdmc937-evt2_audio.dtbo       \
                yupikp-iot-qrd-overlay-stdmc937mipi-dvt_audio.dtbo    \
                yupikp-iot-qrd-overlay-stdmc937mipi-evt2_audio.dtbo   \
                yupikp-iot-qrd-overlay-stdmc937mipi-pvt_audio.dtbo    \
                yupikp-iot-qrd-overlay-stdmc937-pvt_audio.dtbo        \
                yupikp-iot-qrd-overlay-stdmc938-dvt_audio.dtbo \
                yupikp-iot-qrd-overlay-stdmc938-evt2_audio.dtbo \
                yupikp-iot-qrd-overlay-stdmc938-pvt_audio.dtbo \
                katmaip-audio-rb3-gen2-vk-overlay.dtbo \
                katmaip-audio-rb3-gen2-vc-overlay.dtbo
endif


ifeq ($(CONFIG_ARCH_KERA), y)
dtbo-y += kera-audio.dtbo \
                kera-audio-cdp.dtbo \
                kera-iot-audio-cdp.dtbo \
                kera-audio-mtp.dtbo \
                kera-audio-mtp-qmp1000.dtbo \
                kera-audio-qrd.dtbo \
                kera-audio-rcm.dtbo \
                kera-audio-rcm-orne.dtbo

endif

ifeq ($(CONFIG_ARCH_SM6150), y)
dtbo-y += qcs610-audio-iot-overlay.dtbo
endif

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
