# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

# Subdirectories
obj-y += ethernet/stmicro/stmmac/
obj-y += pcs/
obj-y += phy/aquantia/
obj-y += usb/

obj-$(CONFIG_FAILOVER) += failover.o
failover-objs += ../../net/core/failover.o

obj-$(CONFIG_NET_FAILOVER) += net_failover.o

obj-$(CONFIG_VIRTIO_NET) += virtio_net.o
virtio_net-objs += virtio_net_fixed.o

