######################## PN7221 libnfc-nxp-rfExt.conf ########################

###############################################################################
# NXP_NUM_OF_RFEXT_CONFIG : Number of the RF configuration needs to be set.
# MW will read the value of this macro and read the that many config from the
# config file. eg NXP_NUM_OF_RFEXT_CONFIG is 0x02 MW will read NXP_RFEXT_CONFIG_1
# and NXP_RFEXT_CONFIG_2.

NXP_NUM_OF_RFEXT_CONFIG=0x17
###############################################################################
# RF-EXT Configuration, Fill the NXP_RFEXT_CONFIG_x with valid NCI pkt.
# eg. NXP_RFEXT_CONFIG_1={20, 02, 0C, 01, A2, 00, 08, E4, 31, A7, AE, FF, FF, 00, 2A} => UserArea
# eg. NXP_RFEXT_CONFIG_2={20, 02, 0A, 01, A0, 0D, 06, 00, 15, 89, 22, 00, 00}         => ProtocolArea

# UserArea Settings
###############################################################################
NXP_RFEXT_CONFIG_1={20, 02, 0C, 01, A2, 0D, 08, 77, 4A, 01, 14, 6A, 2A, 0A, 07}
NXP_RFEXT_CONFIG_2={20, 02, 0C, 01, A2, 0F, 08, 00, FF, 01, 01, 32, 28, 13, 00}
NXP_RFEXT_CONFIG_3={20, 02, 0C, 01, A2, 10, 08, 00, 28, 13, 00, 00, 28, 13, 00}
NXP_RFEXT_CONFIG_4={20, 02, 0C, 01, A2, 11, 08, 00, 26, 13, 00, 00, 23, 13, 00}
NXP_RFEXT_CONFIG_5={20, 02, 0C, 01, A2, 12, 08, 00, 21, 13, 00, 00, 20, 00, 00}
NXP_RFEXT_CONFIG_6={20, 02, 0C, 01, A2, 13, 08, 00, 1F, 00, 00, 00, 1E, 00, 00}
NXP_RFEXT_CONFIG_7={20, 02, 0C, 01, A2, 14, 08, 00, 1D, 00, 00, 00, 1D, 00, 00}
NXP_RFEXT_CONFIG_8={20, 02, 0C, 01, A2, 15, 08, 00, 1D, 00, 00, 00, 1C, 00, 00}
NXP_RFEXT_CONFIG_9={20, 02, 0C, 01, A2, 16, 08, 00, 1C, 00, 00, 00, 1B, 00, 00}
NXP_RFEXT_CONFIG_10={20, 02, 0C, 01, A2, 17, 08, 00, 1B, 00, 00, 00, 1A, 00, 00}
NXP_RFEXT_CONFIG_11={20, 02, 0C, 01, A2, 18, 08, 00, 1A, 00, 00, 00, 19, 00, 00}
NXP_RFEXT_CONFIG_12={20, 02, 0C, 01, A2, 19, 08, 00, 19, 00, 00, 00, 18, 00, 00}
NXP_RFEXT_CONFIG_13={20, 02, 0C, 01, A2, 1A, 08, 00, 18, 00, 00, 00, 17, 00, 00}
NXP_RFEXT_CONFIG_14={20, 02, 0C, 01, A2, 1B, 08, 00, 17, 00, 00, 00, 16, 00, 00}
NXP_RFEXT_CONFIG_15={20, 02, 0C, 01, A2, 1C, 08, 00, 16, 00, 00, 00, 16, 00, 00}
NXP_RFEXT_CONFIG_16={20, 02, 0C, 01, A2, 1D, 08, 00, 15, 00, 00, 00, 15, 00, 00}
NXP_RFEXT_CONFIG_17={20, 02, 0C, 01, A2, 1E, 08, 00, 14, 00, 00, 00, 13, 00, 00}
NXP_RFEXT_CONFIG_18={20, 02, 0C, 01, A2, 1F, 08, 00, 13, 00, 00, 00, 12, 00, 00}
NXP_RFEXT_CONFIG_19={20, 02, 0C, 01, A2, 20, 08, 00, 12, 00, 00, 00, 12, 00, 00}
NXP_RFEXT_CONFIG_20={20, 02, 0C, 01, A2, 21, 08, 00, 11, 00, 00, 00, 11, 00, 00}
NXP_RFEXT_CONFIG_21={20, 02, 0C, 01, A2, 22, 08, 00, 10, 00, 00, 00, 10, 00, 00}
NXP_RFEXT_CONFIG_22={20, 02, 0C, 01, A2, 23, 08, 00, 0F, 00, 00, 00, 0E, 00, 00}
NXP_RFEXT_CONFIG_23={20, 02, 0C, 01, A2, 24, 08, 00, 0C, 00, 00, 00, 0A, 00, 00}

# ProtocolArea Settings
###############################################################################

###############################################################################
